name: scat_clustering
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=9.2=0
  - matplotlib=3.3.2=0
  - numpy=1.19.2=py37h54aff64_0
  - opencv=3.4.2=py37h6fd60c2_1
  - pandas=1.1.3=py37he6710b0_0
  - pytorch=1.7.0=py3.7_cuda9.2.148_cudnn7.6.3_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37h0b6359f_0
  - torchvision=0.8.1=py37_cu92
  - pip:
    - hnswlib==0.4.0
    - kymatio==0.2.0
    - tqdm==4.52.0
